services:
  mongodb:
    image: mongo:7.0
    container_name: africapharmacy-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - africapharmacy-network
    command: mongod --replSet rs0 --bind_ip_all --noauth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev-only
    container_name: africapharmacy-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database - Updated for replica set (no auth)
      DATABASE_URL: mongodb://mongodb:27017/africapharmacy?replicaSet=rs0
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-d66b1af42b3efd477d99c8babb131ec89e37d6cfcc122314cea614c2fca03f52}
      
      # Email (optional)
      EMAIL_SERVER: ${EMAIL_SERVER:-}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@africapharmacy.local}
      
      # Other environment variables
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      
      # Use local storage for file uploads
      NEXT_PUBLIC_USE_LOCAL_STORAGE: "true"
    depends_on:
      - mongodb
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - africapharmacy-network

  # Optional: MongoDB Express for database management UI
  mongo-express:
    image: mongo-express:latest
    container_name: africapharmacy-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/?replicaSet=rs0
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - africapharmacy-network

volumes:
  mongodb_data:

networks:
  africapharmacy-network:
    driver: bridge